### PR TITLE
Fix such that there is a rollback() before LogicalLock unlock()

### LINKED ISSUE #137: Problems with LogicalLock.
Hello Rob,

with #107 we introduced a "LogicalLock". This means that dbmigration maintains the lock state in the 0-id entry in the lock table.

As long as everything works without errors, the logical lock works fine.

We noted some issues or have the wrong expections:

**Problems**

1. If the server goes away (or the client will be killed), the lock stays always on `locked` and will never get reverted to `<init>`
2. If one of the migration scripts fails partially, the [unlockMigrationTable](https://github.com/ebean-orm/ebean-migration/blob/e998a87268b3a9a849e92e4b1f34b524c8c180e0/ebean-migration/src/main/java/io/ebean/migration/runner/MigrationPlatform.java#L123) performs a commit, which commits the partial work of this script
3. DB2 performs a commit on `reorg table` and mariadb also performs an autocommit on data model changes.

Now, if really something in the migration fails, this costs a lot of effort, to get the app back running.
You should know, that we run our application in financial insititutes, where the DBAs cannot easily access the DB and manipulate some table data - and - as we run the app in a multi tenant setup, where each tenant has its own set of tables, the failure often occurs in more than one tenant. So we need some kind of automation here.

Currently, we have to buld a new application release with new migration scripts (often targeted only to this customer)

**Expectations**

*Commit after each script*
If a script is executed successfully, this should be committed to the DB. I've added a change in #56 - but this was reverted, as it affects locking. Especially, if the DB does an implicit auto commit (and do not use LogicalLock), you may end up with lots executed migration scripts, but not listed in migration table.

*Easier fix of failed migrations*
If scripts fail partially, this is really the worst thing that can happen and if the DB isn't strictly transactional (like mariadb or db2 after a reorg), It would be great, if there is a mechanism, how to control the next DB migration run.
A lot of is already possible with `patchInsertOn` and so on, but I cannot modify existing files without building a new application.
It would be great, if I can ship some patch file (e.g. patch.yml, which is auto detected and may add or override existing migrations)

```yaml
dbmigration:
  files:
    V2_123__blah.sql:
       # this overrides the original V2_123__blah.sql
       - update mytable set fix = 1;
       - update othertable set fix = 1;
  patchinserton:  1.111
```

*Locks never released*
The logical lock may be never released (this is bad for the app-server guy, which has no DB access, as he can not continue with installation.)
We additionally use [Hazelcast-IMap](https://docs.hazelcast.org/docs/4.0/javadoc/com/hazelcast/map/IMap.html#tryLock-K-) in our application, so in our case we can be sure, that only one cluster partner will run the migration code, so in this case, we would not need a lock at all...

@rbygrave maybe you can give some feedback, if I go into the right direction here.

### PR DESCRIPTION
**Pull request by rbygrave**
When there is an error during migration and using logical lock
then ensure there is a rollback before the unlock() on the logical
lock.

### CODE REVIEW

**Comment by rbygrave** [comment]
FYI @rPraml

File: ebean-migration/src/main/java/io/ebean/migration/runner/MigrationEngine.java [hunk 1]
```diff
@@ -44,7 +43,6 @@ public List<MigrationResource> run(Connection connection) {
       }
 
       long startMs = System.currentTimeMillis();
-      connection.setAutoCommit(false);
       MigrationTable table = initialiseMigrationTable(connection);
```
Comment (rPraml) [inline ebean-migration/src/main/java/io/ebean/migration/runner/MigrationEngine.java:46]: I checked obtainLogicalLock, so everything is committed after this line.

File: ebean-migration/src/main/java/io/ebean/migration/runner/MigrationEngine.java [hunk 2]
```diff
@@ -58,30 +56,34 @@ public List<MigrationResource> run(Connection connection) {
           }
         }
         return result;
+      } catch (MigrationException e) {
+        rollback(connection);
+        throw e;
+      } catch (Exception e) {
```
Comment (rPraml) [inline ebean-migration/src/main/java/io/ebean/migration/runner/MigrationEngine.java:62]: Better: catch throwable here
otherwise we may miss assertionErrors in JDBC scripts and so on

File: ebean-migration/src/main/java/io/ebean/migration/runner/MigrationEngine.java [hunk 3]
```diff
@@ -58,30 +56,34 @@ public List<MigrationResource> run(Connection connection) {
...
+      MigrationPlatform platform = derivePlatformName(migrationConfig, connection);
+      new MigrationSchema(migrationConfig, connection).createAndSetIfNeeded();
 
-    final MigrationTable table = new MigrationTable(migrationConfig, connection, checkStateOnly, platform);
-    table.createIfNeededAndLock();
-    return table;
+      final MigrationTable table = new MigrationTable(migrationConfig, connection, checkStateOnly, platform);
+      table.createIfNeededAndLock();
+      return table;
+    } catch (Exception e) {
```
Comment (rPraml) [inline ebean-migration/src/main/java/io/ebean/migration/runner/MigrationEngine.java:83]: Throwable?

**Review by rPraml — COMMENTED** [review]
Hello @rbygrave,

yes this change should fix point 2 in #137, but it would be better, if throwable is catched to catch all possible errors. (e.g. some assertions in JDBC-scripts)

BTW: I would just rethrow the throwable, this may save one additional catch block:
```java
try {
   // run migration
} catch (Throwable t) {
   log.log(ERROR, "Perform rollback due to DB migration error", t);
   rollback(connection);
   throw t; // no need to wrap it in a MigrationException
} finally {
   table.unlockMigrationTable();
}
```

**Comment by rbygrave** [comment]
> just rethrow the throwable

Can't really do that without the checked exception being declared all the way back up.

**Comment by rPraml** [comment]
> > just rethrow the throwable
> 
> Can't really do that without the checked exception being declared all the way back up.

You are right. Didn't see that there are checked exceptions (SQLException) in the try block.
I thought, that this is one of the special cases, where it is possible to rethrow Throwable as mentioned [here](https://stackoverflow.com/questions/23581611/why-is-it-legal-to-re-throw-a-throwable-in-certain-cases-without-declaring-it)
